fix my messed up wait script

diff --git a/start-emulator b/start-emulator
--- a/start-emulator
+++ b/start-emulator
@@ -10,16 +10,17 @@ if [ $# -gt 0 ]; then
   bootanim=""
   failcounter=0
   until [[ "$bootanim" =~ "stopped" ]]; do
-  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
-  echo "$bootanim"
-  if [[ "$bootanim" =~ "not found" ]]; then
+    bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
+    echo "$bootanim"
+    if [[ "$bootanim" =~ "not found" ]]; then
     let "failcounter += 1"
-    if [[ $failcounter -gt 15 ]]; then
-      echo "Failed to start emulator"
-      exit 1
+      if [[ $failcounter -gt 15 ]]; then
+        echo "Failed to start emulator"
+        exit 1
+      fi
     fi
-  fi
-  sleep 1
+    sleep 1
+  done
   echo "Started emulator[$PORT]."
   
   $CMD
